INFO:
  EXCEL_FOLDER: "Excel_Folder"
  EXCEL_DB_MANAGER: "ExcelDBManager"
  FILE_MANAGE: "FileManage"
  MODEL_MANAGE: "ModelManage"
  date_column: "date"
  country_dict:
    kzt: "Kazakhstan"
    rus: "Russia"
    bel: "Belarus"

ModelInfoFields:
  DataSourceInfoFields:
    country: "country"
    sourcetype: "source_type"
    source: "source"
    input_file: "input_file"
    input_sheet: "input_sheet"

  RawDataLocationInfoFields:
    fname: "name"
    is_real: "real"
    is_sa: "sa"

  TransformationInstructionFields:
    transf: "transf"
    calc: "calc"
    is_makesa: "makesa"
    freq: "freq"
    ds: "start"
    de: "end"
    norm_d: "norm"
    output_sheet: "output_sheet"

ModelOutputUnits:
  m: "monthly"
  msa: "monthly_sa"
  q: "quarterly"
  qsa: "quarterly_sa"
  d: "daily"
  a: "annually"
  w: "weekly"
  UnitsValueSet: [m, msa, q, qsa, d, a, w]


StorageInfoFields:
  var_list_sheet: "var_list"
  date_column: "date"
  sheet: "sheet"
  variable: "variable"
  short_name: "short_name"
  RawDataLocation:
    name: "name"
    real: "real"
    sa: "sa"
  RawDataProperties:
    freq: "freq"
    type: "type"
    calc: "calc"
    is_sa: "sa"
  description: "description"
  source: "source"
  country: "country"
  last_date: "last_date"
  position: "position"
  ticker: "ticker"
  category: "category"

TypeValues:
  index: 'index'
  rate: 'rate'
  value: 'value'
  yoy: 'yoy'
  ytd: 'ytd'
  pp: 'pp'
  values_set: ['index','rate','value','yoy','ytd','pp']
FreqValues:
  weekly: 'weekly'
  monthly: 'monthly'
  quarterly: 'quarterly'
  annual: 'annual'
  values_set: ['weekly','monthly','quarterly','annual']
CalcValues:
  eop: 'eop'
  avr: 'avr'
  sum: 'sum'
  values_set: ['eop','avr','sum']

SAValues:
  sa: 'sa'
  nonsa: 'nonsa'

TransformationTypes:
  type: 'type'
  frequency: 'freq'
  normalization: 'norm'
  seasonal_adjustment: 'sa'